### ISSUE TITLE
error: undefined variable 'cfg'

### ISSUE THREAD

**Issue by jalbstmeijer** [nix-community/NixNG#27]
Hi,

Just trying this for the first time.
When following the instructions I get;

```
# nix build .#examples.nix.config.system.build.ociImage.build
error: undefined variable 'cfg'

       at /nix/store/41xdcl17vbvy1hgqh67nl0q090x0wh26-source/modules/system/oci-image.nix:41:18:

           40|         config = {
           41|           name = cfg.name;
             |                  ^
           42|           tag = "latest";
(use '--show-trace' to show detailed location information)
```
Gr, J

**Comment by MagicRB** [comment]
I am currently on a train from Amsterdam to Eindhoven heading by plane to Slovakia. But once I land I'll immediately come and help you out. sorry for the bad first impression :(

Jul 21, 2023 10:19:02 AM jalbstmeijer ***@***.***>:

**Comment by MagicRB** [comment]
The issue is now fixed, please verify on your end and if satisfied feel free to close :) @jalbstmeijer

**Comment by jalbstmeijer** [comment]
Thank you!, that fixed it.
