### ISSUE TITLE
chattr: setting flags on /etc/shadow: Operation not permitted

### ISSUE THREAD

**Issue by pizzapim** [nix-community/NixNG#34]
On multiple of the examples, I see the following error:
```
$ docker run -it nixng-apache
Running fragment cacerts
Running fragment createBaseEnv
Running fragment currentSystem
Running fragment iana
Running fragment runit
Running fragment shellProfile
Running fragment tzdata
Running fragment users
chattr: setting flags on /etc/shadow: Operation not permitted
<--- Stage 2.2 --->
```

It does look like the containers works correctly though!

**Comment by MagicRB** [comment]
Yeah it appears to be a thing with rootless containers, the `/etc/shadow` file is somehow more protected. Haven't looked into it as the containers work as expected, as you have noticed :)

**Comment by pizzapim** [comment]
Can confirm this seems to be an issue with rootless docker. But I don't think it has to do with `/etc/shadow` being more protected, I cannot do `chattr +i` on any file.

**Comment by MagicRB** [comment]
Oh okay, so we just need to detect rootless? Well we could also silence the error but detecting rootless is better.
