### ISSUE TITLE
Using NixNG together with nix-snapshotter?

### ISSUE THREAD

**Issue by ComputeDragon** [nix-community/NixNG#48]
Can NixNG be used together with `nix-snpashotter`  https://github.com/pdtpartners/nix-snapshotter?

This combination would be the best of both worlds. Being able to run and configure k8s apps/deployments using the familiar nix `services.enable = true` syntax, while also eliminating the need to  push and pull the output of NixNG to an OCI registry before the image can be used in k3s/k8s.

**Comment by MagicRB** [comment]
Hey, see https://git.sr.ht/~magic_rb/uk3s.nix a very under-documented project of mine which does something like this. But more specifically see https://git.sr.ht/~magic_rb/dotfiles/tree/master/item/terranix/main/kubernetes/matrix.nix#L23 . Thats how you generate a nix-snapshotter compatible image ref from a NixNG configuration. Its all very very underdocumented, for which i apologize but i struggle to find time for docs.
